"""add models tables

Revision ID: 5bf881552f4e
Revises: 
Create Date: 2026-06-26 00:34:29.893686

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5bf881552f4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=50), nullable=True),
    sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False),
    sa.Column('plan', sa.Enum('free', 'paid', name='userplan'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key')),
    sa.UniqueConstraint('google_id', name=op.f('user_google_id_key'))
    )
    op.create_table('competitor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('main_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('competitor_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('competitor_pkey'))
    )
    op.create_index(op.f('competitor_user_id_idx'), 'competitor', ['user_id'], unique=False)
    op.create_table('schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('frequency', sa.Enum('weekly', 'daily', name='schedulefrequency'), nullable=False),
    sa.Column('day_of_week', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', name='schedulestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('schedule_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('schedule_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('schedule_user_id_key'))
    )
    op.create_table('alert',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('competitor_id', sa.Uuid(), nullable=False),
    sa.Column('signal_type', sa.Enum('pricing', 'feature', 'news', 'social', name='signaltype'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], name=op.f('alert_competitor_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('alert_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_pkey'))
    )
    op.create_index(op.f('alert_competitor_id_idx'), 'alert', ['competitor_id'], unique=False)
    op.create_index(op.f('alert_user_id_idx'), 'alert', ['user_id'], unique=False)
    op.create_table('competitorsource',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('competitor_id', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sa.Enum('website', 'social', 'news', 'review', name='sourcetype'), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], name=op.f('competitorsource_competitor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('competitorsource_pkey'))
    )
    op.create_index(op.f('competitorsource_competitor_id_idx'), 'competitorsource', ['competitor_id'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('competitor_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.Enum('scheduled', 'on_demand', 'alert_scan', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='jobstatus'), nullable=False),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], name=op.f('job_competitor_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('job_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('job_pkey'))
    )
    op.create_index(op.f('job_competitor_id_idx'), 'job', ['competitor_id'], unique=False)
    op.create_index(op.f('job_user_id_idx'), 'job', ['user_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('competitor_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('sources_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='reportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], name=op.f('report_competitor_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('report_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('report_pkey'))
    )
    op.create_index(op.f('report_competitor_id_idx'), 'report', ['competitor_id'], unique=False)
    op.create_index(op.f('report_user_id_idx'), 'report', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name=op.f('feedback_report_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('feedback_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_pkey')),
    sa.UniqueConstraint('report_id', name=op.f('feedback_report_id_key'))
    )
    op.create_index(op.f('feedback_user_id_idx'), 'feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('feedback_user_id_idx'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('report_user_id_idx'), table_name='report')
    op.drop_index(op.f('report_competitor_id_idx'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('job_user_id_idx'), table_name='job')
    op.drop_index(op.f('job_competitor_id_idx'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('competitorsource_competitor_id_idx'), table_name='competitorsource')
    op.drop_table('competitorsource')
    op.drop_index(op.f('alert_user_id_idx'), table_name='alert')
    op.drop_index(op.f('alert_competitor_id_idx'), table_name='alert')
    op.drop_table('alert')
    op.drop_table('schedule')
    op.drop_index(op.f('competitor_user_id_idx'), table_name='competitor')
    op.drop_table('competitor')
    op.drop_table('user')
    # ### end Alembic commands ###
